### ISSUE TITLE
稀疏点云地图导航

### ISSUE THREAD

**Issue by celesius** [izhengfan/se2clam#1]
郑帆您好：
       早先在Youtube上看到过您讲解这个案例的视频，现在现在终于看到源码和论文。感谢感谢。我有个问题：在这类稀疏点云地图上如何做机器人的路径规划呢？我没找到比较合理的方案，希望您这里能给一些建议，谢谢啦：）

**Comment by izhengfan** [comment]
抱歉呀，我不是研究路径规划的，很难给可靠建议。直接在稀疏点云导航似乎不太靠谱，也许可以找找有没有将稀疏点云转成 octomap 的工作，然后用 octomap 来导航？

**Comment by celesius** [comment]
恩，没事没事，可以讨论一下。
octomap的方法之前想过，但这需要我在设备前面增加深度传感器，结合上keyframe优化过的姿态进行点云拼接，然后再在这个octomap中导航。这样做个人感觉太冗余了...给系统带来了不必要的计算负担，必经小车只在一个二维平面中做相对固定的路线行走。
另外，再请问郑帆您们在测试定位精度的时候是如何实现车辆再次到达地图上同一个点的呢？谢谢了:)

**Comment by izhengfan** [comment]
毕竟深度传感器是比较成熟的方案了，稀疏点云的信息量能否用来导航我表示怀疑，更别说我们实验中经常用上视相机来生成稀疏点云，特征点大部分来自天花板和高处物体。

关于 ground truth，我们在地面上贴了密度不小的qr code，增加了一个下视相机来专门看这个 qr code，以此来生成 ground truth

**Comment by celesius** [comment]
好的，谢谢郑帆和你聊天对我们启发很大，太感谢了：）

**Comment by izhengfan** [comment]
好的，good luck
