### ISSUE TITLE
Could this model be used on KITTI odometry dataset ?

### ISSUE THREAD

**Issue by ganleiboy** [izhengfan/se2clam#2]
Your work is great ! Could this model be used on KITTI odometry dataset ? And how to make it ?

**Comment by izhengfan** [comment]
Hello, I am afraid not, KITTI is an outdoor large-scale dataset, and the vehicle motion is not planar.

**Comment by izhengfan** [comment]
Also, it seems KITTI lacks odometric measurements synchronized with images.
