### ISSUE TITLE
some basic questions about this project

### ISSUE THREAD

**Issue by Tofupi** [izhengfan/se2clam#3]
I have read part of source code, It seems no exists initialization process, which is different from ORB_SLAM2. and R t are directly get from odom-2d in triangulate. Local BA part is not read, and it seems use slide window size from what I see in rviz.right? Global BA is alsome and I am curious about it, can you explain it process theory/chart. sorry to bouther you.

**Comment by Tofupi** [comment]
I am thinking it may be a light vision-odom slam for 2D slam and can be apply to vacuum cleaner, do you agree? or do you have other advice about applying this project to vacuum cleaner?

**Comment by izhengfan** [comment]
There no actual init process, odom measurement is directly use as the first guess.

Yes, Local BA is like slide window. And there is also nothing new about global BA, it is just pose graph optimization.

I am not familiar with vacuum cleaner, but I think the method is applicable to any ground vehicles moving on a plane.

**Comment by Tofupi** [comment]
Thanks for your reply.  and in your demo exe, I found no Odom and Image Message Synchronization Mechanism. and it assumes that the two messages have the same timestamp. Anyway, Messages can not be absoutely Synchronized with no diff. have you test SLAM accuracy when messages timestamp exists diff and what's the diff range? sorry to bother you again.

**Comment by izhengfan** [comment]
We have sensors synchronization in the hardware level. Both encoders and industrial camera  can be triggered by a signal sent from a MCU.

**Comment by izhengfan** [comment]
Software synchronization should be ok, but hardware sync is definitely better.

**Comment by Tofupi** [comment]
ok, thank you very much! I 'll try.
