### ISSUE TITLE
Questions about levelCols and levelRows in ORBExtractor

### ISSUE THREAD

**Issue by Tofupi** [izhengfan/se2clam#6]
const int levelCols = sqrt((float)nDesiredFeatures/(5*imageRatio));
const int levelRows = imageRatio*levelCols;

above code pasted from ComputeKeyPoints() function. I want to kown why calc the two value in this way but  they are const variable 30 in ORB_SLAM2 code.
hope for your reply. thanks

**Comment by izhengfan** [comment]
These are from [ORB_SLAM](https://github.com/raulmur/ORB_SLAM/blob/master/src/ORBextractor.cc). I don't know why they did this when upgraded to ORB_SLAM2.

**Comment by Tofupi** [comment]
ok, thanks
