### ISSUE TITLE
Few questions about the equations in the paper

### ISSUE THREAD

**Issue by surfall12** [izhengfan/se2clam#8]
Hi,
    I'm reading the paper and try to understand the equations, but I have few questions about them. Could you please help me to figure it out if you are convenient?
    1. In equation (5), the information matrix is denoted as lowercase omega, however, equation (9) uses both lowercase and capital omega. Do they have the same meaning?
    2. Equation (23), the error in frame {B} is defined as a subtraction of two se3. Why not define it as the same form of equation (22) in camera frame?
    3. Equation (46) is the calculated Hessian matrix "H" for the two keyframes after marginalization.  According to my understanding, using H=J^(T) * Omega * J, the information matrix Omega could be calculated once H and J are known. In the paper, the equation (47) is used to calculate the information matrix with J+.  However, I can't understand the construction of J+. Could you please make it more detailed?

   I would appreciate if you could help me with the questions. Looking forward to you replying.

**Comment by izhengfan** [comment]
Hi,

1. they are the same and should be capital. The lower case is an error (feedback already sent to editors, but no reply).

2. Because odometry measurements are in frame {B}, so the information matrix should be firstly expressed in frame {B} then transformed to {C}.

3.  Using H=J^(T) * Omega * J, you can get H from Omega, but you cannot get Omega from H. J is 6x12 so we need its pseudo-inverse J+ to get Omega from H. You can search pseudoinverse to learn about it .

**Comment by surfall12** [comment]
> Hi,
> 
> 1. they are the same and should be capital. The lower case is an error (feedback already sent to editors, but no reply).
> 2. Because odometry measurements are in frame {B}, so the information matrix should be firstly expressed in frame {B} then transformed to {C}.
> 3. Using H=J^(T) * Omega * J, you can get H from Omega, but you cannot get Omega from H. J is 6x12 so we need its pseudo-inverse J+ to get Omega from H. You can search pseudoinverse to learn about it .

#

**Comment by surfall12** [comment]
Hi, 
   Thanks for your reply.
   But question 2 still confuses me. I might have not made my question clear. Here is an attached  picture which details my question. Looking forward to you replying. Thanks.
![se2lam2](https://user-images.githubusercontent.com/68325577/89020906-4369af00-d352-11ea-8c5c-fda1eb967745.PNG)

**Comment by izhengfan** [comment]
Because Covariance in its definition is LINEAR. When we say Covariance of measurement x’, it’s actually like cov(x’-x)^2

**Comment by surfall12** [comment]
> Because Covariance in its definition is LINEAR. When we say Covariance of measurement x’, it’s actually like cov(x’-x)^2

Sorry, I couldn't understand it yet. Could you please make it more detailed? or give me some clues or reference that could help me with it? Thanks a lot.

**Comment by zhangshuoneu** [comment]
> Because Covariance in its definition is LINEAR. When we say Covariance of measurement x’, it’s actually like cov(x’-x)^2

郑博，你好，我也对这里有一些疑问，这里直接使用运算符号“-”连接两个se3是否欠妥？

**Comment by izhengfan** [comment]
> 

取决于你如何定义cov，是直接定义在 x 上还是 x 的李代数小量（命名不准确，意会）上，实际上都可以

**Comment by izhengfan** [comment]
> > Because Covariance in its definition is LINEAR. When we say Covariance of measurement x’, it’s actually like cov(x’-x)^2
> 
> 郑博，你好，我也对这里有一些疑问，这里直接使用运算符号“-”连接两个se3是否欠妥？


取决于你如何定义cov，是直接定义在 x 上还是 x 的李代数小量（命名不准确，意会）上，实际上都可以
